[package]
name = "msr-plugin"
description = "Industrial Automation Toolbox - Plugins"
license = "MIT/Apache-2.0"
edition = "2018"
version = "0.3.0"

[dependencies]
# Workspace
msr-core = "0.3"

# Other
log = "0.4"
tokio = { version = "1", default_features = false, features = ["sync"] }
