[package]
name = "msr-plugin"
version = "0.3.0"
description = "Industrial Automation library - Plugins"
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2018"

[dependencies]
# Workspace
msr-core = "0.3"

# Other
log = "0.4"
tokio = { version = "1", default_features = false, features = ["sync"] }
