[package]
version = "0.3.4"
name = "msr-plugin"
description = "Industrial Automation Toolbox - Plugin foundation"
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.20", default-features = false, features = ["sync"] }

# Workspace dependencies
msr-core = "=0.3.4"
