[package]
name = "msr-plugin"
description = "Industrial Automation Toolbox - Plugin Foundation"
license = "MIT/Apache-2.0"
edition = "2021"
version = "0.3.0"

[dependencies]
log = "0.4.14"
thiserror = "1.0.30"
tokio = { version = "1.16.1", default-features = false, features = ["sync"] }

# Workspace dependencies
msr-core = "0.3.0"
