[package]
name = "msr"
description = "Industrial Automation library"
version = "0.3.0"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
edition = "2018"

[dependencies]
msr-core = { path = "../msr-core" }
msr-plugin = { path = "../msr-plugin" }

[dev-dependencies]
anyhow = "1"
env_logger = "0.9"
log = "0.4"
tokio = { version = "1", features = ["full"] }
