[package]
name = "msr"
description = "Industrial Automation Toolbox"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
license = "MIT/Apache-2.0"
edition = "2021"
version = "0.3.4"

[dependencies]
# Workspace dependencies
msr-core = "=0.3.4"
msr-plugin = { version = "=0.3.4", optional = true }

[features]
default = []
plugin = ["msr-plugin"]

[dev-dependencies]
anyhow = "1.0"
env_logger = "0.9"
log = "0.4"
tokio = { version = "1.20", features = ["full"] }

# Workspace dev-dependencies
msr-plugin = "=0.3.4"
