[package]
name = "msr"
description = "Industrial Automation Toolbox"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
edition = "2018"
version = "0.3.0"

[dependencies]
# Workspace
msr-core = "*"
msr-plugin = { version = "*", optional = true }

[features]
default = []
plugin = ["msr-plugin"]

[dev-dependencies]
msr = { version = "*", features = ["plugin"] }
anyhow = "1"
env_logger = "0.9"
log = "0.4"
tokio = { version = "1", features = ["full"] }
