[package]
name = "msr"
description = "Industrial Automation Toolbox"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
license = "MIT/Apache-2.0"
edition = "2021"
version = "0.3.0"

[dependencies]
# Workspace
msr-core = "0.3.0"
msr-plugin = { version = "0.3.0", optional = true }

[features]
default = []
with-plugin = ["msr-plugin"]

[dev-dependencies]
msr = { version = "0.3.0", features = ["with-plugin"] }
anyhow = "1.0.55"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.17.0", features = ["full"] }
