[package]
name = "msr"
description = "Industrial Automation Toolbox"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
license = "MIT/Apache-2.0"
edition = "2021"
version = "0.3.1"

[dependencies]
# Workspace dependencies
msr-core = "=0.3.1"
msr-plugin = { version = "=0.3.1", optional = true }

[features]
default = []
with-plugin = ["msr-plugin"]

[dev-dependencies]
anyhow = "1.0.56"
env_logger = "0.9.0"
log = "0.4.16"
tokio = { version = "1.17.0", features = ["full"] }

# Workspace dev-dependencies
msr = { version = "=0.3.1", features = ["with-plugin"] }
