[package]
name = "msr-core"
description = "Industrial Automation Toolbox - Core Components"
license = "MIT/Apache-2.0"
edition = "2018"
version = "0.3.0"

[dependencies]
chrono = "0.4"
clokwerk = "0.3"
log = "0.4"
thiserror = "1"

anyhow = { version = "1", optional = true, default_features = false }
bs58 = { version = "0.4", optional = true, default_features = false }
csv = { version = "1", optional = true, default_features = false }
serde = { version = "1", optional = true, default_features = false }
serde_json = { version = "1", optional = true, default_features = false }
thread-priority = { version = "0.2", optional = true, default_features = false }
uuid = { version = "0.8", optional = true, default_features = false }

[dev-dependencies]
tempfile = "3"

[features]
default = []
event-journal = ["anyhow", "bs58", "chrono/serde", "serde", "uuid/v4"]
register-recorder = ["anyhow", "chrono/serde", "serde", "serde_json"]
csv-storage = ["csv", "serde"]
csv-event-journal = ["event-journal", "csv-storage"]
csv-register-recorder = ["register-recorder", "csv-storage"]
realtime-worker-thread = ["thread-priority"]
