[package]
name = "msr-core"
description = "Industrial automation library"
version = "0.3.0"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
edition = "2018"

[dependencies]
thiserror = "1"

[badges]
maintenance = { status = "actively-developed" }
