[package]
version = "0.3.3"
name = "msr-core"
description = "Industrial Automation Toolbox - Common core components"
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
log = "0.4"
num-derive =  { version = "0.3", default-features = false }
num-traits =  { version = "0.2", default-features = false }
thiserror = "1.0"
time = { version = "0.3", features = ["local-offset", "macros", "formatting", "parsing"] }

bs58 = { version = "0.4", optional = true, default-features = false }
csv = { version = "1.1", optional = true, default-features = false }
serde = { version = "1.0", optional = true, default-features = false }
serde_json = { version = "1.0", optional = true, default-features = false }
thread-priority = { version = "0.9", optional = true, default-features = false }
uuid = { version = "1.1", optional = true, default-features = false }

[target.'cfg(loom)'.dependencies]
loom = "0.5"

[features]
default = []
full = ["csv-event-journal", "csv-register-recorder", "realtime-worker-thread"]
serde = ["dep:serde", "time/serde-well-known"]
event-journal = ["serde/derive", "bs58/std", "uuid/v4"]
register-recorder = ["serde/derive", "bs58/std"]
csv-storage = ["serde", "csv"]
csv-event-journal = ["event-journal", "csv-storage"]
csv-register-recorder = ["register-recorder", "csv-storage"]
realtime-worker-thread = ["thread-priority"]

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.3"
msr-core = { path = ".", features = ["full"] }
