[package]
name = "msr-core"
description = "Industrial Automation Toolbox - Core Components"
license = "MIT/Apache-2.0"
edition = "2021"
version = "0.3.0"

[dependencies]
log = "0.4.14"
parking_lot = "0.12.0"
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["local-offset", "macros"] }

anyhow = { version = "1.0.53", optional = true, default-features = false }
bs58 = { version = "0.4.0", optional = true, default-features = false }
csv = { version = "1.1.6", optional = true, default-features = false }
serde = { version = "1.0.136", optional = true, default-features = false }
serde_json = { version = "1.0.79", optional = true, default-features = false }
thread-priority = { version = "0.7.0", optional = true, default-features = false }
uuid = { version = "0.8.2", optional = true, default-features = false }

[target.'cfg(loom)'.dependencies]
loom = "0.5.4"

[features]
default = []
with-serde = ["serde", "time/serde-well-known"]
event-journal = ["with-serde", "serde/derive", "anyhow/std", "bs58/std", "uuid/v4"]
register-recorder = ["with-serde", "serde/derive", "anyhow/std", "bs58/std", "serde_json/std"]
csv-storage = ["csv", "serde"]
csv-event-journal = ["event-journal", "csv-storage"]
csv-register-recorder = ["register-recorder", "csv-storage"]
realtime-worker-thread = ["anyhow/std", "thread-priority"]

[dev-dependencies]
tempfile = "3.3.0"
msr-core = { version = "0.3.0", features = ["realtime-worker-thread", "csv-event-journal", "csv-register-recorder"] }
