[package]
version = "0.3.1"
name = "msr-core"
description = "Industrial Automation Toolbox - Common core components"
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
base64 = "0.13.0"
log = "0.4.16"
parking_lot = "0.12.0"
thiserror = "1.0.30"
time = { version = "0.3.9", features = ["local-offset", "macros", "formatting", "parsing"] }

bs58 = { version = "0.4.0", optional = true, default-features = false }
csv = { version = "1.1.6", optional = true, default-features = false }
serde = { version = "1.0.136", optional = true, default-features = false }
serde_json = { version = "1.0.79", optional = true, default-features = false }
thread-priority = { version = "0.8.0", optional = true, default-features = false }
uuid = { version = "0.8.2", optional = true, default-features = false }

[target.'cfg(loom)'.dependencies]
loom = "0.5.4"

[features]
default = []
full = ["with-csv-event-journal", "with-csv-register-recorder", "with-realtime-worker-thread"]
with-serde = ["serde", "time/serde-well-known"]
with-event-journal = ["with-serde", "serde/derive", "bs58/std", "uuid/v4"]
with-register-recorder = ["with-serde", "serde/derive", "bs58/std"]
with-csv-storage = ["with-serde", "csv"]
with-csv-event-journal = ["with-event-journal", "with-csv-storage"]
with-csv-register-recorder = ["with-register-recorder", "with-csv-storage"]
with-realtime-worker-thread = ["thread-priority"]

[dev-dependencies]
serde_json = "1.0.79"
tempfile = "3.3.0"
msr-core = { path = ".", features = ["full"] }
