[package]
name = "msr-core"
description = "Industrial Automation library - Core"
version = "0.3.0"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
keywords = ["automation", "control", "plc", "msr", "fieldbus"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"
edition = "2018"

[dependencies]
chrono = "0.4"
clokwerk = "0.3"
csv = { version = "1", optional = true }
log = "0.4"
serde = { version = "1", optional = true }
thiserror = "1"

[dev-dependencies]
tempfile = "3"

[features]
default = ["csv-recording"]
csv-recording = ["csv", "serde"]
