[package]
name = "msr-core"
description = "Industrial Automation Toolbox - Common core components"
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.66"
base64 = "0.13.1"
log = "0.4.17"
num-derive = "0.3.3"
num-traits =  "0.2.15"
thiserror = "1.0.37"
time = { version = "0.3.17", features = ["local-offset", "macros", "formatting", "parsing"] }

bs58 = { version = "0.4.0", optional = true, default-features = false }
csv = { version = "1.1.6", optional = true, default-features = false }
serde = { version = "1.0.147", optional = true, default-features = false }
serde_json = { version = "1.0.87", optional = true, default-features = false }
thread-priority = { version = "0.10.0", optional = true, default-features = false }
ulid = { version = "1.0.0", optional = true }

[target.'cfg(loom)'.dependencies]
loom = "0.5.6"

[features]
default = []
full = ["csv-event-journal", "csv-register-recorder", "realtime-worker-thread"]
serde = ["dep:serde", "time/serde-human-readable"]
event-journal = ["serde/derive", "ulid"]
register-recorder = ["serde/derive", "bs58/std"]
csv-storage = ["serde", "csv"]
csv-event-journal = ["event-journal", "csv-storage"]
csv-register-recorder = ["register-recorder", "csv-storage"]
realtime-worker-thread = ["thread-priority"]

[dev-dependencies]
serde_json = "1.0.87"
tempfile = "3.3.0"
msr-core = { path = ".", features = ["full"] }
