[package]
name = "msr-core"
description = "Industrial Automation Toolbox - Core"
license = "MIT/Apache-2.0"
edition = "2018"
version = "0.3.0"

[dependencies]
chrono = "0.4"
clokwerk = "0.3"
csv = { version = "1", optional = true }
log = "0.4"
serde = { version = "1", optional = true }
thiserror = "1"

[dev-dependencies]
tempfile = "3"

[features]
default = ["csv-recording"]
csv-recording = ["csv", "serde"]
