# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: continuous-integration

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Check msr-core
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --manifest-path crates/msr-core/Cargo.toml

      - name: Check msr-plugin
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --manifest-path crates/msr-plugin/Cargo.toml

      - name: Check msr-legacy
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --manifest-path crates/msr-legacy/Cargo.toml

      - name: Check msr-plugin-csv-event-journal
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --manifest-path plugins/csv-event-journal/Cargo.toml

      - name: Check msr-plugin-csv-register-recorder
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --manifest-path plugins/csv-register-recorder/Cargo.toml

      - name: Build tests with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --workspace --all-features --no-run

      - name: Run tests with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --workspace --all-features -- --nocapture --quiet

      - name: Build release with default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release
